### ISSUE TITLE
Facet 'company activity' (nace) not displayed

### ISSUE THREAD

**Issue by bmzernichow** [euBusinessGraph/eubg-marketplace#1]
In some cases company activity (nace) is not displayed, e.g.:
![image](https://user-images.githubusercontent.com/11430375/60706547-feced280-9f09-11e9-8d04-6895a2f0f666.png)

NACE should always be displayed when available in data:
![image](https://user-images.githubusercontent.com/11430375/60706651-36d61580-9f0a-11e9-937a-21faacf35ddb.png)

**Comment by SBYDeveloper** [comment]
@bmzernichow  this is fixed with the finish of the data reload so at the moment its there and working.

@boyan-simeonov
